'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Image from 'next/image'
import { useSharedReport } from '@/hooks/use-reports'
import { ReportViewer } from '@/components/reports/report-viewer'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Lock, AlertCircle } from 'lucide-react'

export default function SharedReportPage() {
  const params = useParams()
  const shortCode = params.code as string
  const { report, loading, error, requiresPassword, loadReport } = useSharedReport(shortCode)
  const [password, setPassword] = useState('')

  useEffect(() => {
    loadReport()
  }, [shortCode, loadReport])

  const handlePasswordSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await loadReport(password)
  }

  if (loading) {
    return (
      <div className="container max-w-7xl mx-auto py-8 px-4">
        <Skeleton className="h-12 w-64 mb-4" />
        <Skeleton className="h-6 w-48 mb-8" />
        <div className="space-y-4">
          <Skeleton className="h-32 w-full" />
          <Skeleton className="h-64 w-full" />
          <Skeleton className="h-48 w-full" />
        </div>
      </div>
    )
  }

  if (requiresPassword) {
    return (
      <div className="container max-w-md mx-auto py-16 px-4">
        <Card>
          <CardHeader className="text-center">
            <Lock className="w-12 h-12 mx-auto mb-4 text-gray-400" />
            <CardTitle>Password Required</CardTitle>
            <CardDescription>
              This report is password protected. Please enter the password to view it.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handlePasswordSubmit} className="space-y-4">
              <Input
                type="password"
                placeholder="Enter password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
              {error && (
                <p className="text-sm text-red-500">
                  {error}
                </p>
              )}
              <Button type="submit" className="w-full">
                View Report
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    )
  }

  if (error && !requiresPassword) {
    return (
      <div className="container max-w-md mx-auto py-16 px-4">
        <Card>
          <CardHeader className="text-center">
            <AlertCircle className="w-12 h-12 mx-auto mb-4 text-red-500" />
            <CardTitle>Report Not Found</CardTitle>
            <CardDescription>
              {error}
            </CardDescription>
          </CardHeader>
          <CardContent className="text-center">
            <p className="text-sm text-gray-500">
              The report may have expired or the link may be incorrect.
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  if (!report) {
    return null
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="container max-w-7xl mx-auto py-4 px-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Image src="/logo.svg" alt="BeautifyAI" width={32} height={32} className="h-8 w-auto" />
              <span className="text-sm text-gray-500">Shared Report</span>
            </div>
            <p className="text-sm text-gray-500">
              Generated by BeautifyAI
            </p>
          </div>
        </div>
      </div>

      <div className="container max-w-7xl mx-auto py-8 px-4">
        <ReportViewer report={report} />
      </div>

      <footer className="bg-white border-t mt-12">
        <div className="container max-w-7xl mx-auto py-6 px-4 text-center">
          <p className="text-sm text-gray-500">
            Want to enhance your own documents?{' '}
            <a href="https://beautifyai.com" className="text-primary hover:underline">
              Try BeautifyAI for free
            </a>
          </p>
        </div>
      </footer>
    </div>
  )
}