import {
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Circle,
  Copy,
  Download,
  Edit,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  Github,
  Globe,
  Heart,
  Home,
  Image,
  Info,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Trash,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  alertCircle: AlertCircle,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  circle: Circle,
  copy: Copy,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileText: FileText,
  filter: Filter,
  folder: Folder,
  github: Github,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  info: Info,
  loader: Loader2,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  package: Package,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share,
  shoppingCart: ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  trash: Trash,
  trash2: Trash2,
  trendingUp: TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  close: X,
  x: X,
  zap: Zap,
  spinner: Loader2,
} as const